# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='activite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activites',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
