# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170204_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('register', models.BooleanField(default=False)),
                ('single', models.BooleanField(default=True)),
                ('info', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='activite',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='activites',
            field=models.ManyToManyField(blank=True, to='event.Activity'),
        ),
    ]
