# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20170204_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activites',
            field=models.ManyToManyField(blank=True, to='event.Activity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='binets',
            field=models.ManyToManyField(blank=True, to='event.Binet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Section'),
        ),
    ]
