# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170204_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='id',
            field=models.CharField(default='', max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
