# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20170205_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nage',
            old_name='distance',
            new_name='backandforth',
        ),
    ]
