# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20170205_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UselessEmpty',
        ),
    ]
