# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_delete_uselessempty'),
    ]

    operations = [
        migrations.AddField(
            model_name='binet',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
